[2024-12-19T08:51:40.730+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T08:51:40.763+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.second_task scheduled__2021-10-20T00:00:00+00:00 [queued]>
[2024-12-19T08:51:40.793+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.second_task scheduled__2021-10-20T00:00:00+00:00 [queued]>
[2024-12-19T08:51:40.794+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-19T08:51:40.889+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): second_task> on 2021-10-20 00:00:00+00:00
[2024-12-19T08:51:40.913+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2698) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-19T08:51:40.919+0000] {standard_task_runner.py:72} INFO - Started process 2712 to run task
[2024-12-19T08:51:40.922+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'second_task', 'scheduled__2021-10-20T00:00:00+00:00', '--job-id', '525', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpvfi2xvme']
[2024-12-19T08:51:40.931+0000] {standard_task_runner.py:105} INFO - Job 525: Subtask second_task
[2024-12-19T08:51:41.062+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v2.second_task scheduled__2021-10-20T00:00:00+00:00 [running]> on host 8d142e9c83a7
[2024-12-19T08:51:41.254+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mateo' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2021-10-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-10-20T00:00:00+00:00'
[2024-12-19T08:51:41.260+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T08:51:41.326+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-19T08:51:41.336+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo I am the second task and i will me executed after first task']
[2024-12-19T08:51:41.366+0000] {subprocess.py:99} INFO - Output:
[2024-12-19T08:51:41.368+0000] {subprocess.py:106} INFO - I am the second task and i will me executed after first task
[2024-12-19T08:51:41.369+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-19T08:51:41.407+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T08:51:41.408+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=second_task, run_id=scheduled__2021-10-20T00:00:00+00:00, execution_date=20211020T000000, start_date=20241219T085140, end_date=20241219T085141
[2024-12-19T08:51:41.510+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-19T08:51:41.535+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-19T08:51:41.541+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
