[2024-12-19T08:49:05.491+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T08:49:05.547+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.second_task scheduled__2022-03-13T00:00:00+00:00 [queued]>
[2024-12-19T08:49:05.570+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.second_task scheduled__2022-03-13T00:00:00+00:00 [queued]>
[2024-12-19T08:49:05.574+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-19T08:49:05.627+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): second_task> on 2022-03-13 00:00:00+00:00
[2024-12-19T08:49:05.671+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'second_task', 'scheduled__2022-03-13T00:00:00+00:00', '--job-id', '234', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmphw8mz_np']
[2024-12-19T08:49:05.663+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1430) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-19T08:49:05.703+0000] {standard_task_runner.py:72} INFO - Started process 1451 to run task
[2024-12-19T08:49:05.706+0000] {standard_task_runner.py:105} INFO - Job 234: Subtask second_task
[2024-12-19T08:49:05.905+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag.second_task scheduled__2022-03-13T00:00:00+00:00 [running]> on host 8d142e9c83a7
[2024-12-19T08:49:06.188+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mateo' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2022-03-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-03-13T00:00:00+00:00'
[2024-12-19T08:49:06.190+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T08:49:06.227+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-19T08:49:06.234+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo I am the second task and i will me executed after first task']
[2024-12-19T08:49:06.276+0000] {subprocess.py:99} INFO - Output:
[2024-12-19T08:49:06.281+0000] {subprocess.py:106} INFO - I am the second task and i will me executed after first task
[2024-12-19T08:49:06.283+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-19T08:49:06.333+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T08:49:06.335+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag, task_id=second_task, run_id=scheduled__2022-03-13T00:00:00+00:00, execution_date=20220313T000000, start_date=20241219T084905, end_date=20241219T084906
[2024-12-19T08:49:06.413+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-19T08:49:06.440+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-19T08:49:06.449+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
